<?php

use yii\db\Migration;

class m170601_104705_regencies extends Migration
{
    public function up()
    {


$tables = Yii::$app->db->schema->getTableNames();
$dbType = $this->db->driverName;
$tableOptions_mysql = "CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB";
$tableOptions_mssql = "";
$tableOptions_pgsql = "";
$tableOptions_sqlite = "";
/* MYSQL */
if (!in_array('regencies', $tables))  { 
if ($dbType == "mysql") {
    $this->createTable('{{%regencies}}', [
        'regency_id' => 'CHAR(4) NOT NULL',
        0 => 'PRIMARY KEY (`regency_id`)',
        'province_id' => 'CHAR(2) NOT NULL',
        'name' => 'VARCHAR(255) NOT NULL',
    ], $tableOptions_mysql);
}
}
 
 
$this->createIndex('idx_province_id_2927_00','regencies','province_id',0);
 
$this->execute('SET foreign_key_checks = 0');
$this->addForeignKey('fk_provinces_2919_00','{{%regencies}}', 'province_id', '{{%provinces}}', 'province_id', 'CASCADE', 'NO ACTION' );
$this->execute('SET foreign_key_checks = 1;');
 
$this->execute('SET foreign_key_checks = 0');
$this->insert('{{%regencies}}',['regency_id'=>'1101','province_id'=>'11','name'=>'KABUPATEN SIMEULUE']);
$this->insert('{{%regencies}}',['regency_id'=>'1102','province_id'=>'11','name'=>'KABUPATEN ACEH SINGKIL']);
$this->insert('{{%regencies}}',['regency_id'=>'1103','province_id'=>'11','name'=>'KABUPATEN ACEH SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1104','province_id'=>'11','name'=>'KABUPATEN ACEH TENGGARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1105','province_id'=>'11','name'=>'KABUPATEN ACEH TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'1106','province_id'=>'11','name'=>'KABUPATEN ACEH TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'1107','province_id'=>'11','name'=>'KABUPATEN ACEH BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1108','province_id'=>'11','name'=>'KABUPATEN ACEH BESAR']);
$this->insert('{{%regencies}}',['regency_id'=>'1109','province_id'=>'11','name'=>'KABUPATEN PIDIE']);
$this->insert('{{%regencies}}',['regency_id'=>'1110','province_id'=>'11','name'=>'KABUPATEN BIREUEN']);
$this->insert('{{%regencies}}',['regency_id'=>'1111','province_id'=>'11','name'=>'KABUPATEN ACEH UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1112','province_id'=>'11','name'=>'KABUPATEN ACEH BARAT DAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'1113','province_id'=>'11','name'=>'KABUPATEN GAYO LUES']);
$this->insert('{{%regencies}}',['regency_id'=>'1114','province_id'=>'11','name'=>'KABUPATEN ACEH TAMIANG']);
$this->insert('{{%regencies}}',['regency_id'=>'1115','province_id'=>'11','name'=>'KABUPATEN NAGAN RAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'1116','province_id'=>'11','name'=>'KABUPATEN ACEH JAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'1117','province_id'=>'11','name'=>'KABUPATEN BENER MERIAH']);
$this->insert('{{%regencies}}',['regency_id'=>'1118','province_id'=>'11','name'=>'KABUPATEN PIDIE JAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'1171','province_id'=>'11','name'=>'KOTA BANDA ACEH']);
$this->insert('{{%regencies}}',['regency_id'=>'1172','province_id'=>'11','name'=>'KOTA SABANG']);
$this->insert('{{%regencies}}',['regency_id'=>'1173','province_id'=>'11','name'=>'KOTA LANGSA']);
$this->insert('{{%regencies}}',['regency_id'=>'1174','province_id'=>'11','name'=>'KOTA LHOKSEUMAWE']);
$this->insert('{{%regencies}}',['regency_id'=>'1175','province_id'=>'11','name'=>'KOTA SUBULUSSALAM']);
$this->insert('{{%regencies}}',['regency_id'=>'1201','province_id'=>'12','name'=>'KABUPATEN NIAS']);
$this->insert('{{%regencies}}',['regency_id'=>'1202','province_id'=>'12','name'=>'KABUPATEN MANDAILING NATAL']);
$this->insert('{{%regencies}}',['regency_id'=>'1203','province_id'=>'12','name'=>'KABUPATEN TAPANULI SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1204','province_id'=>'12','name'=>'KABUPATEN TAPANULI TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'1205','province_id'=>'12','name'=>'KABUPATEN TAPANULI UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1206','province_id'=>'12','name'=>'KABUPATEN TOBA SAMOSIR']);
$this->insert('{{%regencies}}',['regency_id'=>'1207','province_id'=>'12','name'=>'KABUPATEN LABUHAN BATU']);
$this->insert('{{%regencies}}',['regency_id'=>'1208','province_id'=>'12','name'=>'KABUPATEN ASAHAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1209','province_id'=>'12','name'=>'KABUPATEN SIMALUNGUN']);
$this->insert('{{%regencies}}',['regency_id'=>'1210','province_id'=>'12','name'=>'KABUPATEN DAIRI']);
$this->insert('{{%regencies}}',['regency_id'=>'1211','province_id'=>'12','name'=>'KABUPATEN KARO']);
$this->insert('{{%regencies}}',['regency_id'=>'1212','province_id'=>'12','name'=>'KABUPATEN DELI SERDANG']);
$this->insert('{{%regencies}}',['regency_id'=>'1213','province_id'=>'12','name'=>'KABUPATEN LANGKAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1214','province_id'=>'12','name'=>'KABUPATEN NIAS SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1215','province_id'=>'12','name'=>'KABUPATEN HUMBANG HASUNDUTAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1216','province_id'=>'12','name'=>'KABUPATEN PAKPAK BHARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1217','province_id'=>'12','name'=>'KABUPATEN SAMOSIR']);
$this->insert('{{%regencies}}',['regency_id'=>'1218','province_id'=>'12','name'=>'KABUPATEN SERDANG BEDAGAI']);
$this->insert('{{%regencies}}',['regency_id'=>'1219','province_id'=>'12','name'=>'KABUPATEN BATU BARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1220','province_id'=>'12','name'=>'KABUPATEN PADANG LAWAS UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1221','province_id'=>'12','name'=>'KABUPATEN PADANG LAWAS']);
$this->insert('{{%regencies}}',['regency_id'=>'1222','province_id'=>'12','name'=>'KABUPATEN LABUHAN BATU SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1223','province_id'=>'12','name'=>'KABUPATEN LABUHAN BATU UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1224','province_id'=>'12','name'=>'KABUPATEN NIAS UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1225','province_id'=>'12','name'=>'KABUPATEN NIAS BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1271','province_id'=>'12','name'=>'KOTA SIBOLGA']);
$this->insert('{{%regencies}}',['regency_id'=>'1272','province_id'=>'12','name'=>'KOTA TANJUNG BALAI']);
$this->insert('{{%regencies}}',['regency_id'=>'1273','province_id'=>'12','name'=>'KOTA PEMATANG SIANTAR']);
$this->insert('{{%regencies}}',['regency_id'=>'1274','province_id'=>'12','name'=>'KOTA TEBING TINGGI']);
$this->insert('{{%regencies}}',['regency_id'=>'1275','province_id'=>'12','name'=>'KOTA MEDAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1276','province_id'=>'12','name'=>'KOTA BINJAI']);
$this->insert('{{%regencies}}',['regency_id'=>'1277','province_id'=>'12','name'=>'KOTA PADANGSIDIMPUAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1278','province_id'=>'12','name'=>'KOTA GUNUNGSITOLI']);
$this->insert('{{%regencies}}',['regency_id'=>'1301','province_id'=>'13','name'=>'KABUPATEN KEPULAUAN MENTAWAI']);
$this->insert('{{%regencies}}',['regency_id'=>'1302','province_id'=>'13','name'=>'KABUPATEN PESISIR SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1303','province_id'=>'13','name'=>'KABUPATEN SOLOK']);
$this->insert('{{%regencies}}',['regency_id'=>'1304','province_id'=>'13','name'=>'KABUPATEN SIJUNJUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'1305','province_id'=>'13','name'=>'KABUPATEN TANAH DATAR']);
$this->insert('{{%regencies}}',['regency_id'=>'1306','province_id'=>'13','name'=>'KABUPATEN PADANG PARIAMAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1307','province_id'=>'13','name'=>'KABUPATEN AGAM']);
$this->insert('{{%regencies}}',['regency_id'=>'1308','province_id'=>'13','name'=>'KABUPATEN LIMA PULUH KOTA']);
$this->insert('{{%regencies}}',['regency_id'=>'1309','province_id'=>'13','name'=>'KABUPATEN PASAMAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1310','province_id'=>'13','name'=>'KABUPATEN SOLOK SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1311','province_id'=>'13','name'=>'KABUPATEN DHARMASRAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'1312','province_id'=>'13','name'=>'KABUPATEN PASAMAN BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1371','province_id'=>'13','name'=>'KOTA PADANG']);
$this->insert('{{%regencies}}',['regency_id'=>'1372','province_id'=>'13','name'=>'KOTA SOLOK']);
$this->insert('{{%regencies}}',['regency_id'=>'1373','province_id'=>'13','name'=>'KOTA SAWAH LUNTO']);
$this->insert('{{%regencies}}',['regency_id'=>'1374','province_id'=>'13','name'=>'KOTA PADANG PANJANG']);
$this->insert('{{%regencies}}',['regency_id'=>'1375','province_id'=>'13','name'=>'KOTA BUKITTINGGI']);
$this->insert('{{%regencies}}',['regency_id'=>'1376','province_id'=>'13','name'=>'KOTA PAYAKUMBUH']);
$this->insert('{{%regencies}}',['regency_id'=>'1377','province_id'=>'13','name'=>'KOTA PARIAMAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1401','province_id'=>'14','name'=>'KABUPATEN KUANTAN SINGINGI']);
$this->insert('{{%regencies}}',['regency_id'=>'1402','province_id'=>'14','name'=>'KABUPATEN INDRAGIRI HULU']);
$this->insert('{{%regencies}}',['regency_id'=>'1403','province_id'=>'14','name'=>'KABUPATEN INDRAGIRI HILIR']);
$this->insert('{{%regencies}}',['regency_id'=>'1404','province_id'=>'14','name'=>'KABUPATEN PELALAWAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1405','province_id'=>'14','name'=>'KABUPATEN S I A K']);
$this->insert('{{%regencies}}',['regency_id'=>'1406','province_id'=>'14','name'=>'KABUPATEN KAMPAR']);
$this->insert('{{%regencies}}',['regency_id'=>'1407','province_id'=>'14','name'=>'KABUPATEN ROKAN HULU']);
$this->insert('{{%regencies}}',['regency_id'=>'1408','province_id'=>'14','name'=>'KABUPATEN BENGKALIS']);
$this->insert('{{%regencies}}',['regency_id'=>'1409','province_id'=>'14','name'=>'KABUPATEN ROKAN HILIR']);
$this->insert('{{%regencies}}',['regency_id'=>'1410','province_id'=>'14','name'=>'KABUPATEN KEPULAUAN MERANTI']);
$this->insert('{{%regencies}}',['regency_id'=>'1471','province_id'=>'14','name'=>'KOTA PEKANBARU']);
$this->insert('{{%regencies}}',['regency_id'=>'1473','province_id'=>'14','name'=>'KOTA D U M A I']);
$this->insert('{{%regencies}}',['regency_id'=>'1501','province_id'=>'15','name'=>'KABUPATEN KERINCI']);
$this->insert('{{%regencies}}',['regency_id'=>'1502','province_id'=>'15','name'=>'KABUPATEN MERANGIN']);
$this->insert('{{%regencies}}',['regency_id'=>'1503','province_id'=>'15','name'=>'KABUPATEN SAROLANGUN']);
$this->insert('{{%regencies}}',['regency_id'=>'1504','province_id'=>'15','name'=>'KABUPATEN BATANG HARI']);
$this->insert('{{%regencies}}',['regency_id'=>'1505','province_id'=>'15','name'=>'KABUPATEN MUARO JAMBI']);
$this->insert('{{%regencies}}',['regency_id'=>'1506','province_id'=>'15','name'=>'KABUPATEN TANJUNG JABUNG TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'1507','province_id'=>'15','name'=>'KABUPATEN TANJUNG JABUNG BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1508','province_id'=>'15','name'=>'KABUPATEN TEBO']);
$this->insert('{{%regencies}}',['regency_id'=>'1509','province_id'=>'15','name'=>'KABUPATEN BUNGO']);
$this->insert('{{%regencies}}',['regency_id'=>'1571','province_id'=>'15','name'=>'KOTA JAMBI']);
$this->insert('{{%regencies}}',['regency_id'=>'1572','province_id'=>'15','name'=>'KOTA SUNGAI PENUH']);
$this->insert('{{%regencies}}',['regency_id'=>'1601','province_id'=>'16','name'=>'KABUPATEN OGAN KOMERING ULU']);
$this->insert('{{%regencies}}',['regency_id'=>'1602','province_id'=>'16','name'=>'KABUPATEN OGAN KOMERING ILIR']);
$this->insert('{{%regencies}}',['regency_id'=>'1603','province_id'=>'16','name'=>'KABUPATEN MUARA ENIM']);
$this->insert('{{%regencies}}',['regency_id'=>'1604','province_id'=>'16','name'=>'KABUPATEN LAHAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1605','province_id'=>'16','name'=>'KABUPATEN MUSI RAWAS']);
$this->insert('{{%regencies}}',['regency_id'=>'1606','province_id'=>'16','name'=>'KABUPATEN MUSI BANYUASIN']);
$this->insert('{{%regencies}}',['regency_id'=>'1607','province_id'=>'16','name'=>'KABUPATEN BANYU ASIN']);
$this->insert('{{%regencies}}',['regency_id'=>'1608','province_id'=>'16','name'=>'KABUPATEN OGAN KOMERING ULU SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1609','province_id'=>'16','name'=>'KABUPATEN OGAN KOMERING ULU TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'1610','province_id'=>'16','name'=>'KABUPATEN OGAN ILIR']);
$this->insert('{{%regencies}}',['regency_id'=>'1611','province_id'=>'16','name'=>'KABUPATEN EMPAT LAWANG']);
$this->insert('{{%regencies}}',['regency_id'=>'1612','province_id'=>'16','name'=>'KABUPATEN PENUKAL ABAB LEMATANG ILIR']);
$this->insert('{{%regencies}}',['regency_id'=>'1613','province_id'=>'16','name'=>'KABUPATEN MUSI RAWAS UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1671','province_id'=>'16','name'=>'KOTA PALEMBANG']);
$this->insert('{{%regencies}}',['regency_id'=>'1672','province_id'=>'16','name'=>'KOTA PRABUMULIH']);
$this->insert('{{%regencies}}',['regency_id'=>'1673','province_id'=>'16','name'=>'KOTA PAGAR ALAM']);
$this->insert('{{%regencies}}',['regency_id'=>'1674','province_id'=>'16','name'=>'KOTA LUBUKLINGGAU']);
$this->insert('{{%regencies}}',['regency_id'=>'1701','province_id'=>'17','name'=>'KABUPATEN BENGKULU SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1702','province_id'=>'17','name'=>'KABUPATEN REJANG LEBONG']);
$this->insert('{{%regencies}}',['regency_id'=>'1703','province_id'=>'17','name'=>'KABUPATEN BENGKULU UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1704','province_id'=>'17','name'=>'KABUPATEN KAUR']);
$this->insert('{{%regencies}}',['regency_id'=>'1705','province_id'=>'17','name'=>'KABUPATEN SELUMA']);
$this->insert('{{%regencies}}',['regency_id'=>'1706','province_id'=>'17','name'=>'KABUPATEN MUKOMUKO']);
$this->insert('{{%regencies}}',['regency_id'=>'1707','province_id'=>'17','name'=>'KABUPATEN LEBONG']);
$this->insert('{{%regencies}}',['regency_id'=>'1708','province_id'=>'17','name'=>'KABUPATEN KEPAHIANG']);
$this->insert('{{%regencies}}',['regency_id'=>'1709','province_id'=>'17','name'=>'KABUPATEN BENGKULU TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'1771','province_id'=>'17','name'=>'KOTA BENGKULU']);
$this->insert('{{%regencies}}',['regency_id'=>'1801','province_id'=>'18','name'=>'KABUPATEN LAMPUNG BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1802','province_id'=>'18','name'=>'KABUPATEN TANGGAMUS']);
$this->insert('{{%regencies}}',['regency_id'=>'1803','province_id'=>'18','name'=>'KABUPATEN LAMPUNG SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1804','province_id'=>'18','name'=>'KABUPATEN LAMPUNG TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'1805','province_id'=>'18','name'=>'KABUPATEN LAMPUNG TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'1806','province_id'=>'18','name'=>'KABUPATEN LAMPUNG UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'1807','province_id'=>'18','name'=>'KABUPATEN WAY KANAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1808','province_id'=>'18','name'=>'KABUPATEN TULANGBAWANG']);
$this->insert('{{%regencies}}',['regency_id'=>'1809','province_id'=>'18','name'=>'KABUPATEN PESAWARAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1810','province_id'=>'18','name'=>'KABUPATEN PRINGSEWU']);
$this->insert('{{%regencies}}',['regency_id'=>'1811','province_id'=>'18','name'=>'KABUPATEN MESUJI']);
$this->insert('{{%regencies}}',['regency_id'=>'1812','province_id'=>'18','name'=>'KABUPATEN TULANG BAWANG BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1813','province_id'=>'18','name'=>'KABUPATEN PESISIR BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1871','province_id'=>'18','name'=>'KOTA BANDAR LAMPUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'1872','province_id'=>'18','name'=>'KOTA METRO']);
$this->insert('{{%regencies}}',['regency_id'=>'1901','province_id'=>'19','name'=>'KABUPATEN BANGKA']);
$this->insert('{{%regencies}}',['regency_id'=>'1902','province_id'=>'19','name'=>'KABUPATEN BELITUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'1903','province_id'=>'19','name'=>'KABUPATEN BANGKA BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'1904','province_id'=>'19','name'=>'KABUPATEN BANGKA TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'1905','province_id'=>'19','name'=>'KABUPATEN BANGKA SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'1906','province_id'=>'19','name'=>'KABUPATEN BELITUNG TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'1971','province_id'=>'19','name'=>'KOTA PANGKAL PINANG']);
$this->insert('{{%regencies}}',['regency_id'=>'2101','province_id'=>'21','name'=>'KABUPATEN KARIMUN']);
$this->insert('{{%regencies}}',['regency_id'=>'2102','province_id'=>'21','name'=>'KABUPATEN BINTAN']);
$this->insert('{{%regencies}}',['regency_id'=>'2103','province_id'=>'21','name'=>'KABUPATEN NATUNA']);
$this->insert('{{%regencies}}',['regency_id'=>'2104','province_id'=>'21','name'=>'KABUPATEN LINGGA']);
$this->insert('{{%regencies}}',['regency_id'=>'2105','province_id'=>'21','name'=>'KABUPATEN KEPULAUAN ANAMBAS']);
$this->insert('{{%regencies}}',['regency_id'=>'2171','province_id'=>'21','name'=>'KOTA B A T A M']);
$this->insert('{{%regencies}}',['regency_id'=>'2172','province_id'=>'21','name'=>'KOTA TANJUNG PINANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3101','province_id'=>'31','name'=>'KABUPATEN KEPULAUAN SERIBU']);
$this->insert('{{%regencies}}',['regency_id'=>'3171','province_id'=>'31','name'=>'KOTA JAKARTA SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3172','province_id'=>'31','name'=>'KOTA JAKARTA TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'3173','province_id'=>'31','name'=>'KOTA JAKARTA PUSAT']);
$this->insert('{{%regencies}}',['regency_id'=>'3174','province_id'=>'31','name'=>'KOTA JAKARTA BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'3175','province_id'=>'31','name'=>'KOTA JAKARTA UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'3201','province_id'=>'32','name'=>'KABUPATEN BOGOR']);
$this->insert('{{%regencies}}',['regency_id'=>'3202','province_id'=>'32','name'=>'KABUPATEN SUKABUMI']);
$this->insert('{{%regencies}}',['regency_id'=>'3203','province_id'=>'32','name'=>'KABUPATEN CIANJUR']);
$this->insert('{{%regencies}}',['regency_id'=>'3204','province_id'=>'32','name'=>'KABUPATEN BANDUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'3205','province_id'=>'32','name'=>'KABUPATEN GARUT']);
$this->insert('{{%regencies}}',['regency_id'=>'3206','province_id'=>'32','name'=>'KABUPATEN TASIKMALAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'3207','province_id'=>'32','name'=>'KABUPATEN CIAMIS']);
$this->insert('{{%regencies}}',['regency_id'=>'3208','province_id'=>'32','name'=>'KABUPATEN KUNINGAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3209','province_id'=>'32','name'=>'KABUPATEN CIREBON']);
$this->insert('{{%regencies}}',['regency_id'=>'3210','province_id'=>'32','name'=>'KABUPATEN MAJALENGKA']);
$this->insert('{{%regencies}}',['regency_id'=>'3211','province_id'=>'32','name'=>'KABUPATEN SUMEDANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3212','province_id'=>'32','name'=>'KABUPATEN INDRAMAYU']);
$this->insert('{{%regencies}}',['regency_id'=>'3213','province_id'=>'32','name'=>'KABUPATEN SUBANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3214','province_id'=>'32','name'=>'KABUPATEN PURWAKARTA']);
$this->insert('{{%regencies}}',['regency_id'=>'3215','province_id'=>'32','name'=>'KABUPATEN KARAWANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3216','province_id'=>'32','name'=>'KABUPATEN BEKASI']);
$this->insert('{{%regencies}}',['regency_id'=>'3217','province_id'=>'32','name'=>'KABUPATEN BANDUNG BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'3218','province_id'=>'32','name'=>'KABUPATEN PANGANDARAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3271','province_id'=>'32','name'=>'KOTA BOGOR']);
$this->insert('{{%regencies}}',['regency_id'=>'3272','province_id'=>'32','name'=>'KOTA SUKABUMI']);
$this->insert('{{%regencies}}',['regency_id'=>'3273','province_id'=>'32','name'=>'KOTA BANDUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'3274','province_id'=>'32','name'=>'KOTA CIREBON']);
$this->insert('{{%regencies}}',['regency_id'=>'3275','province_id'=>'32','name'=>'KOTA BEKASI']);
$this->insert('{{%regencies}}',['regency_id'=>'3276','province_id'=>'32','name'=>'KOTA DEPOK']);
$this->insert('{{%regencies}}',['regency_id'=>'3277','province_id'=>'32','name'=>'KOTA CIMAHI']);
$this->insert('{{%regencies}}',['regency_id'=>'3278','province_id'=>'32','name'=>'KOTA TASIKMALAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'3279','province_id'=>'32','name'=>'KOTA BANJAR']);
$this->insert('{{%regencies}}',['regency_id'=>'3301','province_id'=>'33','name'=>'KABUPATEN CILACAP']);
$this->insert('{{%regencies}}',['regency_id'=>'3302','province_id'=>'33','name'=>'KABUPATEN BANYUMAS']);
$this->insert('{{%regencies}}',['regency_id'=>'3303','province_id'=>'33','name'=>'KABUPATEN PURBALINGGA']);
$this->insert('{{%regencies}}',['regency_id'=>'3304','province_id'=>'33','name'=>'KABUPATEN BANJARNEGARA']);
$this->insert('{{%regencies}}',['regency_id'=>'3305','province_id'=>'33','name'=>'KABUPATEN KEBUMEN']);
$this->insert('{{%regencies}}',['regency_id'=>'3306','province_id'=>'33','name'=>'KABUPATEN PURWOREJO']);
$this->insert('{{%regencies}}',['regency_id'=>'3307','province_id'=>'33','name'=>'KABUPATEN WONOSOBO']);
$this->insert('{{%regencies}}',['regency_id'=>'3308','province_id'=>'33','name'=>'KABUPATEN MAGELANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3309','province_id'=>'33','name'=>'KABUPATEN BOYOLALI']);
$this->insert('{{%regencies}}',['regency_id'=>'3310','province_id'=>'33','name'=>'KABUPATEN KLATEN']);
$this->insert('{{%regencies}}',['regency_id'=>'3311','province_id'=>'33','name'=>'KABUPATEN SUKOHARJO']);
$this->insert('{{%regencies}}',['regency_id'=>'3312','province_id'=>'33','name'=>'KABUPATEN WONOGIRI']);
$this->insert('{{%regencies}}',['regency_id'=>'3313','province_id'=>'33','name'=>'KABUPATEN KARANGANYAR']);
$this->insert('{{%regencies}}',['regency_id'=>'3314','province_id'=>'33','name'=>'KABUPATEN SRAGEN']);
$this->insert('{{%regencies}}',['regency_id'=>'3315','province_id'=>'33','name'=>'KABUPATEN GROBOGAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3316','province_id'=>'33','name'=>'KABUPATEN BLORA']);
$this->insert('{{%regencies}}',['regency_id'=>'3317','province_id'=>'33','name'=>'KABUPATEN REMBANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3318','province_id'=>'33','name'=>'KABUPATEN PATI']);
$this->insert('{{%regencies}}',['regency_id'=>'3319','province_id'=>'33','name'=>'KABUPATEN KUDUS']);
$this->insert('{{%regencies}}',['regency_id'=>'3320','province_id'=>'33','name'=>'KABUPATEN JEPARA']);
$this->insert('{{%regencies}}',['regency_id'=>'3321','province_id'=>'33','name'=>'KABUPATEN DEMAK']);
$this->insert('{{%regencies}}',['regency_id'=>'3322','province_id'=>'33','name'=>'KABUPATEN SEMARANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3323','province_id'=>'33','name'=>'KABUPATEN TEMANGGUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'3324','province_id'=>'33','name'=>'KABUPATEN KENDAL']);
$this->insert('{{%regencies}}',['regency_id'=>'3325','province_id'=>'33','name'=>'KABUPATEN BATANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3326','province_id'=>'33','name'=>'KABUPATEN PEKALONGAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3327','province_id'=>'33','name'=>'KABUPATEN PEMALANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3328','province_id'=>'33','name'=>'KABUPATEN TEGAL']);
$this->insert('{{%regencies}}',['regency_id'=>'3329','province_id'=>'33','name'=>'KABUPATEN BREBES']);
$this->insert('{{%regencies}}',['regency_id'=>'3371','province_id'=>'33','name'=>'KOTA MAGELANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3372','province_id'=>'33','name'=>'KOTA SURAKARTA']);
$this->insert('{{%regencies}}',['regency_id'=>'3373','province_id'=>'33','name'=>'KOTA SALATIGA']);
$this->insert('{{%regencies}}',['regency_id'=>'3374','province_id'=>'33','name'=>'KOTA SEMARANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3375','province_id'=>'33','name'=>'KOTA PEKALONGAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3376','province_id'=>'33','name'=>'KOTA TEGAL']);
$this->insert('{{%regencies}}',['regency_id'=>'3401','province_id'=>'34','name'=>'KABUPATEN KULON PROGO']);
$this->insert('{{%regencies}}',['regency_id'=>'3402','province_id'=>'34','name'=>'KABUPATEN BANTUL']);
$this->insert('{{%regencies}}',['regency_id'=>'3403','province_id'=>'34','name'=>'KABUPATEN GUNUNG KIDUL']);
$this->insert('{{%regencies}}',['regency_id'=>'3404','province_id'=>'34','name'=>'KABUPATEN SLEMAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3471','province_id'=>'34','name'=>'KOTA YOGYAKARTA']);
$this->insert('{{%regencies}}',['regency_id'=>'3501','province_id'=>'35','name'=>'KABUPATEN PACITAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3502','province_id'=>'35','name'=>'KABUPATEN PONOROGO']);
$this->insert('{{%regencies}}',['regency_id'=>'3503','province_id'=>'35','name'=>'KABUPATEN TRENGGALEK']);
$this->insert('{{%regencies}}',['regency_id'=>'3504','province_id'=>'35','name'=>'KABUPATEN TULUNGAGUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'3505','province_id'=>'35','name'=>'KABUPATEN BLITAR']);
$this->insert('{{%regencies}}',['regency_id'=>'3506','province_id'=>'35','name'=>'KABUPATEN KEDIRI']);
$this->insert('{{%regencies}}',['regency_id'=>'3507','province_id'=>'35','name'=>'KABUPATEN MALANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3508','province_id'=>'35','name'=>'KABUPATEN LUMAJANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3509','province_id'=>'35','name'=>'KABUPATEN JEMBER']);
$this->insert('{{%regencies}}',['regency_id'=>'3510','province_id'=>'35','name'=>'KABUPATEN BANYUWANGI']);
$this->insert('{{%regencies}}',['regency_id'=>'3511','province_id'=>'35','name'=>'KABUPATEN BONDOWOSO']);
$this->insert('{{%regencies}}',['regency_id'=>'3512','province_id'=>'35','name'=>'KABUPATEN SITUBONDO']);
$this->insert('{{%regencies}}',['regency_id'=>'3513','province_id'=>'35','name'=>'KABUPATEN PROBOLINGGO']);
$this->insert('{{%regencies}}',['regency_id'=>'3514','province_id'=>'35','name'=>'KABUPATEN PASURUAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3515','province_id'=>'35','name'=>'KABUPATEN SIDOARJO']);
$this->insert('{{%regencies}}',['regency_id'=>'3516','province_id'=>'35','name'=>'KABUPATEN MOJOKERTO']);
$this->insert('{{%regencies}}',['regency_id'=>'3517','province_id'=>'35','name'=>'KABUPATEN JOMBANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3518','province_id'=>'35','name'=>'KABUPATEN NGANJUK']);
$this->insert('{{%regencies}}',['regency_id'=>'3519','province_id'=>'35','name'=>'KABUPATEN MADIUN']);
$this->insert('{{%regencies}}',['regency_id'=>'3520','province_id'=>'35','name'=>'KABUPATEN MAGETAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3521','province_id'=>'35','name'=>'KABUPATEN NGAWI']);
$this->insert('{{%regencies}}',['regency_id'=>'3522','province_id'=>'35','name'=>'KABUPATEN BOJONEGORO']);
$this->insert('{{%regencies}}',['regency_id'=>'3523','province_id'=>'35','name'=>'KABUPATEN TUBAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3524','province_id'=>'35','name'=>'KABUPATEN LAMONGAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3525','province_id'=>'35','name'=>'KABUPATEN GRESIK']);
$this->insert('{{%regencies}}',['regency_id'=>'3526','province_id'=>'35','name'=>'KABUPATEN BANGKALAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3527','province_id'=>'35','name'=>'KABUPATEN SAMPANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3528','province_id'=>'35','name'=>'KABUPATEN PAMEKASAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3529','province_id'=>'35','name'=>'KABUPATEN SUMENEP']);
$this->insert('{{%regencies}}',['regency_id'=>'3571','province_id'=>'35','name'=>'KOTA KEDIRI']);
$this->insert('{{%regencies}}',['regency_id'=>'3572','province_id'=>'35','name'=>'KOTA BLITAR']);
$this->insert('{{%regencies}}',['regency_id'=>'3573','province_id'=>'35','name'=>'KOTA MALANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3574','province_id'=>'35','name'=>'KOTA PROBOLINGGO']);
$this->insert('{{%regencies}}',['regency_id'=>'3575','province_id'=>'35','name'=>'KOTA PASURUAN']);
$this->insert('{{%regencies}}',['regency_id'=>'3576','province_id'=>'35','name'=>'KOTA MOJOKERTO']);
$this->insert('{{%regencies}}',['regency_id'=>'3577','province_id'=>'35','name'=>'KOTA MADIUN']);
$this->insert('{{%regencies}}',['regency_id'=>'3578','province_id'=>'35','name'=>'KOTA SURABAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'3579','province_id'=>'35','name'=>'KOTA BATU']);
$this->insert('{{%regencies}}',['regency_id'=>'3601','province_id'=>'36','name'=>'KABUPATEN PANDEGLANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3602','province_id'=>'36','name'=>'KABUPATEN LEBAK']);
$this->insert('{{%regencies}}',['regency_id'=>'3603','province_id'=>'36','name'=>'KABUPATEN TANGERANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3604','province_id'=>'36','name'=>'KABUPATEN SERANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3671','province_id'=>'36','name'=>'KOTA TANGERANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3672','province_id'=>'36','name'=>'KOTA CILEGON']);
$this->insert('{{%regencies}}',['regency_id'=>'3673','province_id'=>'36','name'=>'KOTA SERANG']);
$this->insert('{{%regencies}}',['regency_id'=>'3674','province_id'=>'36','name'=>'KOTA TANGERANG SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'5101','province_id'=>'51','name'=>'KABUPATEN JEMBRANA']);
$this->insert('{{%regencies}}',['regency_id'=>'5102','province_id'=>'51','name'=>'KABUPATEN TABANAN']);
$this->insert('{{%regencies}}',['regency_id'=>'5103','province_id'=>'51','name'=>'KABUPATEN BADUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'5104','province_id'=>'51','name'=>'KABUPATEN GIANYAR']);
$this->insert('{{%regencies}}',['regency_id'=>'5105','province_id'=>'51','name'=>'KABUPATEN KLUNGKUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'5106','province_id'=>'51','name'=>'KABUPATEN BANGLI']);
$this->insert('{{%regencies}}',['regency_id'=>'5107','province_id'=>'51','name'=>'KABUPATEN KARANG ASEM']);
$this->insert('{{%regencies}}',['regency_id'=>'5108','province_id'=>'51','name'=>'KABUPATEN BULELENG']);
$this->insert('{{%regencies}}',['regency_id'=>'5171','province_id'=>'51','name'=>'KOTA DENPASAR']);
$this->insert('{{%regencies}}',['regency_id'=>'5201','province_id'=>'52','name'=>'KABUPATEN LOMBOK BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'5202','province_id'=>'52','name'=>'KABUPATEN LOMBOK TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'5203','province_id'=>'52','name'=>'KABUPATEN LOMBOK TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'5204','province_id'=>'52','name'=>'KABUPATEN SUMBAWA']);
$this->insert('{{%regencies}}',['regency_id'=>'5205','province_id'=>'52','name'=>'KABUPATEN DOMPU']);
$this->insert('{{%regencies}}',['regency_id'=>'5206','province_id'=>'52','name'=>'KABUPATEN BIMA']);
$this->insert('{{%regencies}}',['regency_id'=>'5207','province_id'=>'52','name'=>'KABUPATEN SUMBAWA BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'5208','province_id'=>'52','name'=>'KABUPATEN LOMBOK UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'5271','province_id'=>'52','name'=>'KOTA MATARAM']);
$this->insert('{{%regencies}}',['regency_id'=>'5272','province_id'=>'52','name'=>'KOTA BIMA']);
$this->insert('{{%regencies}}',['regency_id'=>'5301','province_id'=>'53','name'=>'KABUPATEN SUMBA BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'5302','province_id'=>'53','name'=>'KABUPATEN SUMBA TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'5303','province_id'=>'53','name'=>'KABUPATEN KUPANG']);
$this->insert('{{%regencies}}',['regency_id'=>'5304','province_id'=>'53','name'=>'KABUPATEN TIMOR TENGAH SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'5305','province_id'=>'53','name'=>'KABUPATEN TIMOR TENGAH UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'5306','province_id'=>'53','name'=>'KABUPATEN BELU']);
$this->insert('{{%regencies}}',['regency_id'=>'5307','province_id'=>'53','name'=>'KABUPATEN ALOR']);
$this->insert('{{%regencies}}',['regency_id'=>'5308','province_id'=>'53','name'=>'KABUPATEN LEMBATA']);
$this->insert('{{%regencies}}',['regency_id'=>'5309','province_id'=>'53','name'=>'KABUPATEN FLORES TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'5310','province_id'=>'53','name'=>'KABUPATEN SIKKA']);
$this->insert('{{%regencies}}',['regency_id'=>'5311','province_id'=>'53','name'=>'KABUPATEN ENDE']);
$this->insert('{{%regencies}}',['regency_id'=>'5312','province_id'=>'53','name'=>'KABUPATEN NGADA']);
$this->insert('{{%regencies}}',['regency_id'=>'5313','province_id'=>'53','name'=>'KABUPATEN MANGGARAI']);
$this->insert('{{%regencies}}',['regency_id'=>'5314','province_id'=>'53','name'=>'KABUPATEN ROTE NDAO']);
$this->insert('{{%regencies}}',['regency_id'=>'5315','province_id'=>'53','name'=>'KABUPATEN MANGGARAI BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'5316','province_id'=>'53','name'=>'KABUPATEN SUMBA TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'5317','province_id'=>'53','name'=>'KABUPATEN SUMBA BARAT DAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'5318','province_id'=>'53','name'=>'KABUPATEN NAGEKEO']);
$this->insert('{{%regencies}}',['regency_id'=>'5319','province_id'=>'53','name'=>'KABUPATEN MANGGARAI TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'5320','province_id'=>'53','name'=>'KABUPATEN SABU RAIJUA']);
$this->insert('{{%regencies}}',['regency_id'=>'5321','province_id'=>'53','name'=>'KABUPATEN MALAKA']);
$this->insert('{{%regencies}}',['regency_id'=>'5371','province_id'=>'53','name'=>'KOTA KUPANG']);
$this->insert('{{%regencies}}',['regency_id'=>'6101','province_id'=>'61','name'=>'KABUPATEN SAMBAS']);
$this->insert('{{%regencies}}',['regency_id'=>'6102','province_id'=>'61','name'=>'KABUPATEN BENGKAYANG']);
$this->insert('{{%regencies}}',['regency_id'=>'6103','province_id'=>'61','name'=>'KABUPATEN LANDAK']);
$this->insert('{{%regencies}}',['regency_id'=>'6104','province_id'=>'61','name'=>'KABUPATEN MEMPAWAH']);
$this->insert('{{%regencies}}',['regency_id'=>'6105','province_id'=>'61','name'=>'KABUPATEN SANGGAU']);
$this->insert('{{%regencies}}',['regency_id'=>'6106','province_id'=>'61','name'=>'KABUPATEN KETAPANG']);
$this->insert('{{%regencies}}',['regency_id'=>'6107','province_id'=>'61','name'=>'KABUPATEN SINTANG']);
$this->insert('{{%regencies}}',['regency_id'=>'6108','province_id'=>'61','name'=>'KABUPATEN KAPUAS HULU']);
$this->insert('{{%regencies}}',['regency_id'=>'6109','province_id'=>'61','name'=>'KABUPATEN SEKADAU']);
$this->insert('{{%regencies}}',['regency_id'=>'6110','province_id'=>'61','name'=>'KABUPATEN MELAWI']);
$this->insert('{{%regencies}}',['regency_id'=>'6111','province_id'=>'61','name'=>'KABUPATEN KAYONG UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'6112','province_id'=>'61','name'=>'KABUPATEN KUBU RAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'6171','province_id'=>'61','name'=>'KOTA PONTIANAK']);
$this->insert('{{%regencies}}',['regency_id'=>'6172','province_id'=>'61','name'=>'KOTA SINGKAWANG']);
$this->insert('{{%regencies}}',['regency_id'=>'6201','province_id'=>'62','name'=>'KABUPATEN KOTAWARINGIN BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'6202','province_id'=>'62','name'=>'KABUPATEN KOTAWARINGIN TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'6203','province_id'=>'62','name'=>'KABUPATEN KAPUAS']);
$this->insert('{{%regencies}}',['regency_id'=>'6204','province_id'=>'62','name'=>'KABUPATEN BARITO SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'6205','province_id'=>'62','name'=>'KABUPATEN BARITO UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'6206','province_id'=>'62','name'=>'KABUPATEN SUKAMARA']);
$this->insert('{{%regencies}}',['regency_id'=>'6207','province_id'=>'62','name'=>'KABUPATEN LAMANDAU']);
$this->insert('{{%regencies}}',['regency_id'=>'6208','province_id'=>'62','name'=>'KABUPATEN SERUYAN']);
$this->insert('{{%regencies}}',['regency_id'=>'6209','province_id'=>'62','name'=>'KABUPATEN KATINGAN']);
$this->insert('{{%regencies}}',['regency_id'=>'6210','province_id'=>'62','name'=>'KABUPATEN PULANG PISAU']);
$this->insert('{{%regencies}}',['regency_id'=>'6211','province_id'=>'62','name'=>'KABUPATEN GUNUNG MAS']);
$this->insert('{{%regencies}}',['regency_id'=>'6212','province_id'=>'62','name'=>'KABUPATEN BARITO TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'6213','province_id'=>'62','name'=>'KABUPATEN MURUNG RAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'6271','province_id'=>'62','name'=>'KOTA PALANGKA RAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'6301','province_id'=>'63','name'=>'KABUPATEN TANAH LAUT']);
$this->insert('{{%regencies}}',['regency_id'=>'6302','province_id'=>'63','name'=>'KABUPATEN KOTA BARU']);
$this->insert('{{%regencies}}',['regency_id'=>'6303','province_id'=>'63','name'=>'KABUPATEN BANJAR']);
$this->insert('{{%regencies}}',['regency_id'=>'6304','province_id'=>'63','name'=>'KABUPATEN BARITO KUALA']);
$this->insert('{{%regencies}}',['regency_id'=>'6305','province_id'=>'63','name'=>'KABUPATEN TAPIN']);
$this->insert('{{%regencies}}',['regency_id'=>'6306','province_id'=>'63','name'=>'KABUPATEN HULU SUNGAI SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'6307','province_id'=>'63','name'=>'KABUPATEN HULU SUNGAI TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'6308','province_id'=>'63','name'=>'KABUPATEN HULU SUNGAI UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'6309','province_id'=>'63','name'=>'KABUPATEN TABALONG']);
$this->insert('{{%regencies}}',['regency_id'=>'6310','province_id'=>'63','name'=>'KABUPATEN TANAH BUMBU']);
$this->insert('{{%regencies}}',['regency_id'=>'6311','province_id'=>'63','name'=>'KABUPATEN BALANGAN']);
$this->insert('{{%regencies}}',['regency_id'=>'6371','province_id'=>'63','name'=>'KOTA BANJARMASIN']);
$this->insert('{{%regencies}}',['regency_id'=>'6372','province_id'=>'63','name'=>'KOTA BANJAR BARU']);
$this->insert('{{%regencies}}',['regency_id'=>'6401','province_id'=>'64','name'=>'KABUPATEN PASER']);
$this->insert('{{%regencies}}',['regency_id'=>'6402','province_id'=>'64','name'=>'KABUPATEN KUTAI BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'6403','province_id'=>'64','name'=>'KABUPATEN KUTAI KARTANEGARA']);
$this->insert('{{%regencies}}',['regency_id'=>'6404','province_id'=>'64','name'=>'KABUPATEN KUTAI TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'6405','province_id'=>'64','name'=>'KABUPATEN BERAU']);
$this->insert('{{%regencies}}',['regency_id'=>'6409','province_id'=>'64','name'=>'KABUPATEN PENAJAM PASER UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'6411','province_id'=>'64','name'=>'KABUPATEN MAHAKAM HULU']);
$this->insert('{{%regencies}}',['regency_id'=>'6471','province_id'=>'64','name'=>'KOTA BALIKPAPAN']);
$this->insert('{{%regencies}}',['regency_id'=>'6472','province_id'=>'64','name'=>'KOTA SAMARINDA']);
$this->insert('{{%regencies}}',['regency_id'=>'6474','province_id'=>'64','name'=>'KOTA BONTANG']);
$this->insert('{{%regencies}}',['regency_id'=>'6501','province_id'=>'65','name'=>'KABUPATEN MALINAU']);
$this->insert('{{%regencies}}',['regency_id'=>'6502','province_id'=>'65','name'=>'KABUPATEN BULUNGAN']);
$this->insert('{{%regencies}}',['regency_id'=>'6503','province_id'=>'65','name'=>'KABUPATEN TANA TIDUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'6504','province_id'=>'65','name'=>'KABUPATEN NUNUKAN']);
$this->insert('{{%regencies}}',['regency_id'=>'6571','province_id'=>'65','name'=>'KOTA TARAKAN']);
$this->insert('{{%regencies}}',['regency_id'=>'7101','province_id'=>'71','name'=>'KABUPATEN BOLAANG MONGONDOW']);
$this->insert('{{%regencies}}',['regency_id'=>'7102','province_id'=>'71','name'=>'KABUPATEN MINAHASA']);
$this->insert('{{%regencies}}',['regency_id'=>'7103','province_id'=>'71','name'=>'KABUPATEN KEPULAUAN SANGIHE']);
$this->insert('{{%regencies}}',['regency_id'=>'7104','province_id'=>'71','name'=>'KABUPATEN KEPULAUAN TALAUD']);
$this->insert('{{%regencies}}',['regency_id'=>'7105','province_id'=>'71','name'=>'KABUPATEN MINAHASA SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'7106','province_id'=>'71','name'=>'KABUPATEN MINAHASA UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7107','province_id'=>'71','name'=>'KABUPATEN BOLAANG MONGONDOW UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7108','province_id'=>'71','name'=>'KABUPATEN SIAU TAGULANDANG BIARO']);
$this->insert('{{%regencies}}',['regency_id'=>'7109','province_id'=>'71','name'=>'KABUPATEN MINAHASA TENGGARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7110','province_id'=>'71','name'=>'KABUPATEN BOLAANG MONGONDOW SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'7111','province_id'=>'71','name'=>'KABUPATEN BOLAANG MONGONDOW TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'7171','province_id'=>'71','name'=>'KOTA MANADO']);
$this->insert('{{%regencies}}',['regency_id'=>'7172','province_id'=>'71','name'=>'KOTA BITUNG']);
$this->insert('{{%regencies}}',['regency_id'=>'7173','province_id'=>'71','name'=>'KOTA TOMOHON']);
$this->insert('{{%regencies}}',['regency_id'=>'7174','province_id'=>'71','name'=>'KOTA KOTAMOBAGU']);
$this->insert('{{%regencies}}',['regency_id'=>'7201','province_id'=>'72','name'=>'KABUPATEN BANGGAI KEPULAUAN']);
$this->insert('{{%regencies}}',['regency_id'=>'7202','province_id'=>'72','name'=>'KABUPATEN BANGGAI']);
$this->insert('{{%regencies}}',['regency_id'=>'7203','province_id'=>'72','name'=>'KABUPATEN MOROWALI']);
$this->insert('{{%regencies}}',['regency_id'=>'7204','province_id'=>'72','name'=>'KABUPATEN POSO']);
$this->insert('{{%regencies}}',['regency_id'=>'7205','province_id'=>'72','name'=>'KABUPATEN DONGGALA']);
$this->insert('{{%regencies}}',['regency_id'=>'7206','province_id'=>'72','name'=>'KABUPATEN TOLI-TOLI']);
$this->insert('{{%regencies}}',['regency_id'=>'7207','province_id'=>'72','name'=>'KABUPATEN BUOL']);
$this->insert('{{%regencies}}',['regency_id'=>'7208','province_id'=>'72','name'=>'KABUPATEN PARIGI MOUTONG']);
$this->insert('{{%regencies}}',['regency_id'=>'7209','province_id'=>'72','name'=>'KABUPATEN TOJO UNA-UNA']);
$this->insert('{{%regencies}}',['regency_id'=>'7210','province_id'=>'72','name'=>'KABUPATEN SIGI']);
$this->insert('{{%regencies}}',['regency_id'=>'7211','province_id'=>'72','name'=>'KABUPATEN BANGGAI LAUT']);
$this->insert('{{%regencies}}',['regency_id'=>'7212','province_id'=>'72','name'=>'KABUPATEN MOROWALI UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7271','province_id'=>'72','name'=>'KOTA PALU']);
$this->insert('{{%regencies}}',['regency_id'=>'7301','province_id'=>'73','name'=>'KABUPATEN KEPULAUAN SELAYAR']);
$this->insert('{{%regencies}}',['regency_id'=>'7302','province_id'=>'73','name'=>'KABUPATEN BULUKUMBA']);
$this->insert('{{%regencies}}',['regency_id'=>'7303','province_id'=>'73','name'=>'KABUPATEN BANTAENG']);
$this->insert('{{%regencies}}',['regency_id'=>'7304','province_id'=>'73','name'=>'KABUPATEN JENEPONTO']);
$this->insert('{{%regencies}}',['regency_id'=>'7305','province_id'=>'73','name'=>'KABUPATEN TAKALAR']);
$this->insert('{{%regencies}}',['regency_id'=>'7306','province_id'=>'73','name'=>'KABUPATEN GOWA']);
$this->insert('{{%regencies}}',['regency_id'=>'7307','province_id'=>'73','name'=>'KABUPATEN SINJAI']);
$this->insert('{{%regencies}}',['regency_id'=>'7308','province_id'=>'73','name'=>'KABUPATEN MAROS']);
$this->insert('{{%regencies}}',['regency_id'=>'7309','province_id'=>'73','name'=>'KABUPATEN PANGKAJENE DAN KEPULAUAN']);
$this->insert('{{%regencies}}',['regency_id'=>'7310','province_id'=>'73','name'=>'KABUPATEN BARRU']);
$this->insert('{{%regencies}}',['regency_id'=>'7311','province_id'=>'73','name'=>'KABUPATEN BONE']);
$this->insert('{{%regencies}}',['regency_id'=>'7312','province_id'=>'73','name'=>'KABUPATEN SOPPENG']);
$this->insert('{{%regencies}}',['regency_id'=>'7313','province_id'=>'73','name'=>'KABUPATEN WAJO']);
$this->insert('{{%regencies}}',['regency_id'=>'7314','province_id'=>'73','name'=>'KABUPATEN SIDENRENG RAPPANG']);
$this->insert('{{%regencies}}',['regency_id'=>'7315','province_id'=>'73','name'=>'KABUPATEN PINRANG']);
$this->insert('{{%regencies}}',['regency_id'=>'7316','province_id'=>'73','name'=>'KABUPATEN ENREKANG']);
$this->insert('{{%regencies}}',['regency_id'=>'7317','province_id'=>'73','name'=>'KABUPATEN LUWU']);
$this->insert('{{%regencies}}',['regency_id'=>'7318','province_id'=>'73','name'=>'KABUPATEN TANA TORAJA']);
$this->insert('{{%regencies}}',['regency_id'=>'7322','province_id'=>'73','name'=>'KABUPATEN LUWU UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7325','province_id'=>'73','name'=>'KABUPATEN LUWU TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'7326','province_id'=>'73','name'=>'KABUPATEN TORAJA UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7371','province_id'=>'73','name'=>'KOTA MAKASSAR']);
$this->insert('{{%regencies}}',['regency_id'=>'7372','province_id'=>'73','name'=>'KOTA PAREPARE']);
$this->insert('{{%regencies}}',['regency_id'=>'7373','province_id'=>'73','name'=>'KOTA PALOPO']);
$this->insert('{{%regencies}}',['regency_id'=>'7401','province_id'=>'74','name'=>'KABUPATEN BUTON']);
$this->insert('{{%regencies}}',['regency_id'=>'7402','province_id'=>'74','name'=>'KABUPATEN MUNA']);
$this->insert('{{%regencies}}',['regency_id'=>'7403','province_id'=>'74','name'=>'KABUPATEN KONAWE']);
$this->insert('{{%regencies}}',['regency_id'=>'7404','province_id'=>'74','name'=>'KABUPATEN KOLAKA']);
$this->insert('{{%regencies}}',['regency_id'=>'7405','province_id'=>'74','name'=>'KABUPATEN KONAWE SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'7406','province_id'=>'74','name'=>'KABUPATEN BOMBANA']);
$this->insert('{{%regencies}}',['regency_id'=>'7407','province_id'=>'74','name'=>'KABUPATEN WAKATOBI']);
$this->insert('{{%regencies}}',['regency_id'=>'7408','province_id'=>'74','name'=>'KABUPATEN KOLAKA UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7409','province_id'=>'74','name'=>'KABUPATEN BUTON UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7410','province_id'=>'74','name'=>'KABUPATEN KONAWE UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7411','province_id'=>'74','name'=>'KABUPATEN KOLAKA TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'7412','province_id'=>'74','name'=>'KABUPATEN KONAWE KEPULAUAN']);
$this->insert('{{%regencies}}',['regency_id'=>'7413','province_id'=>'74','name'=>'KABUPATEN MUNA BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'7414','province_id'=>'74','name'=>'KABUPATEN BUTON TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'7415','province_id'=>'74','name'=>'KABUPATEN BUTON SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'7471','province_id'=>'74','name'=>'KOTA KENDARI']);
$this->insert('{{%regencies}}',['regency_id'=>'7472','province_id'=>'74','name'=>'KOTA BAUBAU']);
$this->insert('{{%regencies}}',['regency_id'=>'7501','province_id'=>'75','name'=>'KABUPATEN BOALEMO']);
$this->insert('{{%regencies}}',['regency_id'=>'7502','province_id'=>'75','name'=>'KABUPATEN GORONTALO']);
$this->insert('{{%regencies}}',['regency_id'=>'7503','province_id'=>'75','name'=>'KABUPATEN POHUWATO']);
$this->insert('{{%regencies}}',['regency_id'=>'7504','province_id'=>'75','name'=>'KABUPATEN BONE BOLANGO']);
$this->insert('{{%regencies}}',['regency_id'=>'7505','province_id'=>'75','name'=>'KABUPATEN GORONTALO UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7571','province_id'=>'75','name'=>'KOTA GORONTALO']);
$this->insert('{{%regencies}}',['regency_id'=>'7601','province_id'=>'76','name'=>'KABUPATEN MAJENE']);
$this->insert('{{%regencies}}',['regency_id'=>'7602','province_id'=>'76','name'=>'KABUPATEN POLEWALI MANDAR']);
$this->insert('{{%regencies}}',['regency_id'=>'7603','province_id'=>'76','name'=>'KABUPATEN MAMASA']);
$this->insert('{{%regencies}}',['regency_id'=>'7604','province_id'=>'76','name'=>'KABUPATEN MAMUJU']);
$this->insert('{{%regencies}}',['regency_id'=>'7605','province_id'=>'76','name'=>'KABUPATEN MAMUJU UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'7606','province_id'=>'76','name'=>'KABUPATEN MAMUJU TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'8101','province_id'=>'81','name'=>'KABUPATEN MALUKU TENGGARA BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'8102','province_id'=>'81','name'=>'KABUPATEN MALUKU TENGGARA']);
$this->insert('{{%regencies}}',['regency_id'=>'8103','province_id'=>'81','name'=>'KABUPATEN MALUKU TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'8104','province_id'=>'81','name'=>'KABUPATEN BURU']);
$this->insert('{{%regencies}}',['regency_id'=>'8105','province_id'=>'81','name'=>'KABUPATEN KEPULAUAN ARU']);
$this->insert('{{%regencies}}',['regency_id'=>'8106','province_id'=>'81','name'=>'KABUPATEN SERAM BAGIAN BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'8107','province_id'=>'81','name'=>'KABUPATEN SERAM BAGIAN TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'8108','province_id'=>'81','name'=>'KABUPATEN MALUKU BARAT DAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'8109','province_id'=>'81','name'=>'KABUPATEN BURU SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'8171','province_id'=>'81','name'=>'KOTA AMBON']);
$this->insert('{{%regencies}}',['regency_id'=>'8172','province_id'=>'81','name'=>'KOTA TUAL']);
$this->insert('{{%regencies}}',['regency_id'=>'8201','province_id'=>'82','name'=>'KABUPATEN HALMAHERA BARAT']);
$this->insert('{{%regencies}}',['regency_id'=>'8202','province_id'=>'82','name'=>'KABUPATEN HALMAHERA TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'8203','province_id'=>'82','name'=>'KABUPATEN KEPULAUAN SULA']);
$this->insert('{{%regencies}}',['regency_id'=>'8204','province_id'=>'82','name'=>'KABUPATEN HALMAHERA SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'8205','province_id'=>'82','name'=>'KABUPATEN HALMAHERA UTARA']);
$this->insert('{{%regencies}}',['regency_id'=>'8206','province_id'=>'82','name'=>'KABUPATEN HALMAHERA TIMUR']);
$this->insert('{{%regencies}}',['regency_id'=>'8207','province_id'=>'82','name'=>'KABUPATEN PULAU MOROTAI']);
$this->insert('{{%regencies}}',['regency_id'=>'8208','province_id'=>'82','name'=>'KABUPATEN PULAU TALIABU']);
$this->insert('{{%regencies}}',['regency_id'=>'8271','province_id'=>'82','name'=>'KOTA TERNATE']);
$this->insert('{{%regencies}}',['regency_id'=>'8272','province_id'=>'82','name'=>'KOTA TIDORE KEPULAUAN']);
$this->insert('{{%regencies}}',['regency_id'=>'9101','province_id'=>'91','name'=>'KABUPATEN FAKFAK']);
$this->insert('{{%regencies}}',['regency_id'=>'9102','province_id'=>'91','name'=>'KABUPATEN KAIMANA']);
$this->insert('{{%regencies}}',['regency_id'=>'9103','province_id'=>'91','name'=>'KABUPATEN TELUK WONDAMA']);
$this->insert('{{%regencies}}',['regency_id'=>'9104','province_id'=>'91','name'=>'KABUPATEN TELUK BINTUNI']);
$this->insert('{{%regencies}}',['regency_id'=>'9105','province_id'=>'91','name'=>'KABUPATEN MANOKWARI']);
$this->insert('{{%regencies}}',['regency_id'=>'9106','province_id'=>'91','name'=>'KABUPATEN SORONG SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'9107','province_id'=>'91','name'=>'KABUPATEN SORONG']);
$this->insert('{{%regencies}}',['regency_id'=>'9108','province_id'=>'91','name'=>'KABUPATEN RAJA AMPAT']);
$this->insert('{{%regencies}}',['regency_id'=>'9109','province_id'=>'91','name'=>'KABUPATEN TAMBRAUW']);
$this->insert('{{%regencies}}',['regency_id'=>'9110','province_id'=>'91','name'=>'KABUPATEN MAYBRAT']);
$this->insert('{{%regencies}}',['regency_id'=>'9111','province_id'=>'91','name'=>'KABUPATEN MANOKWARI SELATAN']);
$this->insert('{{%regencies}}',['regency_id'=>'9112','province_id'=>'91','name'=>'KABUPATEN PEGUNUNGAN ARFAK']);
$this->insert('{{%regencies}}',['regency_id'=>'9171','province_id'=>'91','name'=>'KOTA SORONG']);
$this->insert('{{%regencies}}',['regency_id'=>'9401','province_id'=>'94','name'=>'KABUPATEN MERAUKE']);
$this->insert('{{%regencies}}',['regency_id'=>'9402','province_id'=>'94','name'=>'KABUPATEN JAYAWIJAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'9403','province_id'=>'94','name'=>'KABUPATEN JAYAPURA']);
$this->insert('{{%regencies}}',['regency_id'=>'9404','province_id'=>'94','name'=>'KABUPATEN NABIRE']);
$this->insert('{{%regencies}}',['regency_id'=>'9408','province_id'=>'94','name'=>'KABUPATEN KEPULAUAN YAPEN']);
$this->insert('{{%regencies}}',['regency_id'=>'9409','province_id'=>'94','name'=>'KABUPATEN BIAK NUMFOR']);
$this->insert('{{%regencies}}',['regency_id'=>'9410','province_id'=>'94','name'=>'KABUPATEN PANIAI']);
$this->insert('{{%regencies}}',['regency_id'=>'9411','province_id'=>'94','name'=>'KABUPATEN PUNCAK JAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'9412','province_id'=>'94','name'=>'KABUPATEN MIMIKA']);
$this->insert('{{%regencies}}',['regency_id'=>'9413','province_id'=>'94','name'=>'KABUPATEN BOVEN DIGOEL']);
$this->insert('{{%regencies}}',['regency_id'=>'9414','province_id'=>'94','name'=>'KABUPATEN MAPPI']);
$this->insert('{{%regencies}}',['regency_id'=>'9415','province_id'=>'94','name'=>'KABUPATEN ASMAT']);
$this->insert('{{%regencies}}',['regency_id'=>'9416','province_id'=>'94','name'=>'KABUPATEN YAHUKIMO']);
$this->insert('{{%regencies}}',['regency_id'=>'9417','province_id'=>'94','name'=>'KABUPATEN PEGUNUNGAN BINTANG']);
$this->insert('{{%regencies}}',['regency_id'=>'9418','province_id'=>'94','name'=>'KABUPATEN TOLIKARA']);
$this->insert('{{%regencies}}',['regency_id'=>'9419','province_id'=>'94','name'=>'KABUPATEN SARMI']);
$this->insert('{{%regencies}}',['regency_id'=>'9420','province_id'=>'94','name'=>'KABUPATEN KEEROM']);
$this->insert('{{%regencies}}',['regency_id'=>'9426','province_id'=>'94','name'=>'KABUPATEN WAROPEN']);
$this->insert('{{%regencies}}',['regency_id'=>'9427','province_id'=>'94','name'=>'KABUPATEN SUPIORI']);
$this->insert('{{%regencies}}',['regency_id'=>'9428','province_id'=>'94','name'=>'KABUPATEN MAMBERAMO RAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'9429','province_id'=>'94','name'=>'KABUPATEN NDUGA']);
$this->insert('{{%regencies}}',['regency_id'=>'9430','province_id'=>'94','name'=>'KABUPATEN LANNY JAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'9431','province_id'=>'94','name'=>'KABUPATEN MAMBERAMO TENGAH']);
$this->insert('{{%regencies}}',['regency_id'=>'9432','province_id'=>'94','name'=>'KABUPATEN YALIMO']);
$this->insert('{{%regencies}}',['regency_id'=>'9433','province_id'=>'94','name'=>'KABUPATEN PUNCAK']);
$this->insert('{{%regencies}}',['regency_id'=>'9434','province_id'=>'94','name'=>'KABUPATEN DOGIYAI']);
$this->insert('{{%regencies}}',['regency_id'=>'9435','province_id'=>'94','name'=>'KABUPATEN INTAN JAYA']);
$this->insert('{{%regencies}}',['regency_id'=>'9436','province_id'=>'94','name'=>'KABUPATEN DEIYAI']);
$this->insert('{{%regencies}}',['regency_id'=>'9471','province_id'=>'94','name'=>'KOTA JAYAPURA']);
$this->execute('SET foreign_key_checks = 1;');

    }

    public function down()
    {

        $this->execute('SET foreign_key_checks = 0');
        $this->execute('DROP TABLE IF EXISTS `regencies`');
        $this->execute('SET foreign_key_checks = 1;');

    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
